version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sprockets
    versions:
    - 4.0.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: netlify-cms
    versions:
    - 2.10.108
    - 2.10.96
    - 2.10.99
  - dependency-name: uswds
    versions:
    - 2.10.2
