backend:
  name: github
  repo: 18f/formservice-trainingmaterials
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: develop

media_folder: assets/uploads
public_folder: /assets/uploads
publish_mode: editorial_workflow
logo_url: https://federalist.18f.gov/assets/images/federalist-logo.png

collections:
  - label: Posts
    name: posts
    folder: _posts/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
      
  - label: Documentation
    name: documentation
    folder: _documentation/
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: "Title", name: "title", widget: "string"}
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - {label: "Body", name: "body", widget: "markdown"}
  - label: Getting Started
    name: getting-started
    folder: _documentation/getting-started/
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: 'Parent', name: 'parent', widget: 'hidden', default: 'getting-started'}
      - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'post'}
      - {label: 'Sidenav', name: 'sidenav', widget: 'hidden', default: true}
      - {label: 'Weight', name: 'weight', widget: "number", valueType: 'int', required: false}
      - {label: "Body", name: "body", widget: "markdown"}
